repos:

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.3
    hooks:
      - id: clang-format
        name: Clang Format
        args: [--style=file]
        files: \.(cpp|hpp|h|c|cc)$

  - repo: local
    hooks:
      - id: cppcheck
        name: Cppcheck
        entry: cppcheck --force --quiet --inline-suppr --suppress=unknownMacro:athena_motor_interface/include/athena_motor_interface/athena_motor_interfaces.h --error-exitcode=1 --language=c++
        language: system
        types: [c, c++]
        files: \.(cpp|hpp|h|c|cc)$

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: Black
        language_version: python3
