/**:
  ros__parameters:
    port_name: "/dev/tty_drive_motor_controller"
    wheel_separation: 1.248
    wheel_radius: 0.075
    left_velocity_pid.k_p: 8.0
    left_velocity_pid.k_i: 6.0
    left_velocity_pid.k_d: 0.0
    right_velocity_pid.k_p: 8.0
    right_velocity_pid.k_i: 6.0
    right_velocity_pid.k_d: 0.0
    left_position_pid.k_p: 10.0
    left_position_pid.k_i: 10.0
    left_position_pid.k_d: 0.0
    right_position_pid.k_p: 10.0
    right_position_pid.k_i: 10.0
    right_position_pid.k_d: 0.0
